### ISSUE TITLE
Not an issue!

### ISSUE THREAD

**Issue by spences10** [nikkilr88/twitter-bot#1]
Like the bot 👍 

I found this, which I have found particularly helpful: https://github.com/nikkilr88/twitter-bot/blob/4231f796762c3279f6c83c191a3003252a25d140/app.js#L61

I'd like to use that in my personal bot and the bootstrap I have for twitter bots or I'd love it if you wanted to make a PR?

My repo is here: https://github.com/spences10/twitter-bot-bootstrap

It currently implements that logic badly and I'd like the previously mentioned in there 

Thanks 😄

**Comment by nikkilr88** [comment]
Thanks! Sorry, I'm just seeing your comment now. I will have a look tomorrow morning. :)
